<?php $this->load->view('includes/header'); ?>

<div id="terms_service">

	<h1>Terms & Conditions</h1>

	<h3>The gist:</h3>
	<p>We (the folks at IWAAT) run a blog and web site hosting service called <a href="http://IWAAT.com">IWAAT.com</a> and would <strong>love</strong> for you to use it. Our basic service is free and designed to give you as much control and ownership over your data as possible and encourage you to express yourself freely. However, be responsible in what you publish. In particular, make sure that none of the prohibited items listed below appear in the data you store on IWAAT (things like spam, viruses, or hate content).</p>
	
	<p>Below is our Terms of Service. <a href="http://creativecommons.org/licenses/by-sa/2.5/" rel="license"><img src="http://creativecommons.org/images/public/somerights20" alt="Creative Commons License" align="right" border="0" /></a> This document is based upon the <a href="http://en.wordpress.com/tos/">Automattic Terms of Service</a> and is licensed under <a href="http://creativecommons.org/licenses/by-sa/2.5/">Creative Commons Attribution Share-Alike License 2.5</a>. Basically, this means you can use it verbatim or edited, but you must release new versions under the same license and you have to credit Automattic somewhere (like this!). Automattic is not connected with and does not sponsor or endorse IWAAT or its use of the work.</p>
	
	<h3>Terms of Service:</h3>
	<p>The following terms and conditions govern all use of the IWAAT.com website and all content, services and products available at or through the website. The Website is owned and operated by I Want An App That (“IWAAT”). The Website is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies (including, without limitation, <a href="/privacy_policy">IWAAT’s Privacy Policy</a>) and procedures that may be published from time to time on this Site by IWAAT (collectively, the “Agreement”).</p>
	<p>Please read this Agreement carefully before accessing or using the Website. By accessing or using any part of the web site, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access the Website or use any services. If these terms and conditions are considered an offer by IWAAT, acceptance is expressly limited to these terms. The Website is available only to individuals who are at least 13 years old.</p>
	
	<ol>
	
	<li><strong>Your IWAAT.com Account and Site.</strong> If you create an account on the Website, you are responsible for maintaining the security of your account, and you are fully responsible for all activities that occur under the account and any other actions taken in connection with it. You must not describe or assign keywords to your applications in a misleading or unlawful manner, including in a manner intended to trade on the name or reputation of others, and IWAAT may change or remove any description or keyword that it considers inappropriate or unlawful, or otherwise likely to cause IWAAT liability. You must immediately notify IWAAT of any unauthorized uses of your account or any other breaches of security. IWAAT will not be liable for any acts or omissions by You, including any damages of any kind incurred as a result of such acts or omissions.</li>
	
	<li><strong>Responsibility of Contributors.</strong>If you make (or allow any third party to make) material available by means of the Website (any such material, “Content”), You are entirely responsible for the content of, and any harm resulting from, that Content. That is the case regardless of whether the Content in question constitutes text, graphics, an audio file, or computer software. By making Content available, you represent and warrant that:
	<ul>
	<li>the downloading, copying and use of the Content will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark or trade secret rights, of any third party;</li>
	<li>if your employer has rights to intellectual property you create, you have either (i) received permission from your employer to post or make available the Content, including but not limited to any software, or (ii) secured from your employer a waiver as to all rights in or to the Content;</li>
	<li>you have fully complied with any third-party licenses relating to the Content, and have done all things necessary to successfully pass through to end users any required terms;</li>
	<li>the Content does not contain or install any viruses, worms, malware, Trojan horses or other harmful or destructive content;</li>
	<li class="important">the Content is not spam, is not machine- or randomly-generated, and does not contain unethical or unwanted commercial content designed to drive traffic to third party sites or boost the search engine rankings of third party sites, or to further unlawful acts (such as phishing) or mislead recipients as to the source of the material (such as spoofing);</li>
	<li>the Content is not pornographic, does not contain threats or incite violence towards individuals or entities, and does not violate the privacy or publicity rights of any third party;</li>
	<li>your application is not getting advertised via unwanted electronic messages such as spam links on newsgroups, email lists, other blogs and web sites, and similar unsolicited promotional methods;</li>
	<li>your application is not named in a manner that misleads your readers into thinking that you are another person or company. For example, your application&#8217;s URL or name is not the name of a person other than yourself or company other than your own; and</li>
	<li>you have, in the case of Content that includes computer code, accurately categorized and/or described the type, nature, uses and effects of the materials, whether requested to do so by IWAAT or otherwise.</li>
	</ul>
	<p>By submitting Content to IWAAT for inclusion on your Website, you grant IWAAT a world-wide, royalty-free, and non-exclusive license to reproduce, modify, adapt and publish the Content solely for the purpose of displaying, distributing and promoting your application. If you delete Content, IWAAT will use reasonable efforts to remove it from the Website, but you acknowledge that caching or references to the Content may not be made immediately unavailable.</p>
	<p>Without limiting any of those representations or warranties, IWAAT has the right (though not the obligation) to, in IWAAT’s sole discretion (i) refuse or remove any content that, in IWAAT’s reasonable opinion, violates any IWAAT policy or is in any way harmful or objectionable, or (ii) terminate or deny access to and use of the Website to any individual or entity for any reason, in IWAAT’s sole discretion. IWAAT will have no obligation to provide a refund of any amounts previously paid.</li>
	
	<li><strong>Payment and Renewal.</strong>
	<ul>
	<li><strong>General Terms. </strong><br />
	Optional paid services may be available on the Website (any such services, an &#8220;Upgrade&#8221;). By selecting an Upgrade you agree to pay IWAAT the daily, monthly, annual or one-time fees indicated for that service. Upgrade fees are not refundable.</li>
	<li><strong>Automatic Renewal. </strong><br />
	Unless you notify IWAAT before the end of the applicable subscription period that you want to cancel an Upgrade, your Upgrade subscription will automatically renew and you authorize us to collect the then-applicable annual or monthly subscription fee for such Upgrade (as well as any taxes) using any credit card or other payment mechanism we have on record for you.</li>
	</ul>
	</li>

	<li><strong>Responsibility of Website Visitors.</strong> IWAAT has not reviewed, and cannot review, all of the material, including computer software, posted to the Website, and cannot therefore be responsible for that material’s content, use or effects. By operating the Website, IWAAT does not represent or imply that it endorses the material there posted, or that it believes such material to be accurate, useful or non-harmful. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. The Website may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. The Website may also contain material that violates the privacy or publicity rights, or infringes the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which is subject to additional terms and conditions, stated or unstated. IWAAT disclaims any responsibility for any harm resulting from the use by visitors of the Website, or from any downloading by those visitors of content there posted.</li>
	
	<li><strong>Content Posted on Other Websites.</strong> We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and webpages to which IWAAT.com links, and that link to IWAAT.com. IWAAT does not have any control over those websites and webpages, and is not responsible for their contents or their use. By linking to a website or webpage, IWAAT does not represent or imply that it endorses such website or webpage. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. IWAAT disclaims any responsibility for any harm resulting from your use of other websites and webpages.</li>
	
	<li><strong>Intellectual Property.</strong> This Agreement does not transfer from IWAAT to you any IWAAT or third party intellectual property, and all right, title and interest in and to such property will remain (as between the parties) solely with IWAAT. IWAAT, IWAAT.com, the IWAAT.com logo, and all other trademarks, service marks, graphics and logos used in connection with IWAAT.com, or the Website are trademarks or registered trademarks of IWAAT or IWAAT’s licensors. Other trademarks, service marks, graphics and logos used in connection with the Website may be the trademarks of other third parties. Your use of the Website grants you no right or license to reproduce or otherwise use any IWAAT or third-party trademarks.</li>
	
	<li><strong>Advertisements.</strong> IWAAT reserves the right to display advertisements on its website.</li>
	
	<li><strong>Changes. </strong>IWAAT reserves the right, at its sole discretion, to modify or replace any part of this Agreement. It is your responsibility to check this Agreement periodically for changes. Your continued use of or access to the Website following the posting of any changes to this Agreement constitutes acceptance of those changes. IWAAT may also, in the future, offer new services and/or features through the Website (including, the release of new tools and resources). Such new features and/or services shall be subject to the terms and conditions of this Agreement. <strong><br />
	</strong></li>
	<li><strong>Termination. </strong>IWAAT may terminate your access to all or any part of the Website at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this Agreement or your IWAAT.com account (if you have one), you may simply discontinue using the Website. IWAAT can terminate the Website immediately as part of a general shut down of our service. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability. <strong><br />
	</strong></li>
	<li class="important"><strong>Disclaimer of Warranties.</strong> The Website is provided &#8220;as is&#8221;. IWAAT and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither IWAAT nor its suppliers and licensors, makes any warranty that the Website will be error free or that access thereto will be continuous or uninterrupted. You understand that you download from, or otherwise obtain content or services through, the Website at your own discretion and risk.</li>
	<li class="important"><strong>Limitation of Liability.</strong> In no event will IWAAT, or its suppliers or licensors, be liable with respect to any subject matter of this agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement for substitute products or services; (iii) for interruption of use or loss or corruption of data; or (iv) for any amounts that exceed the fees paid by you to IWAAT under this agreement during the twelve (12) month period prior to the cause of action. IWAAT shall have no liability for any failure or delay due to matters beyond their reasonable control. The foregoing shall not apply to the extent prohibited by applicable law.</li>
	<li><strong>General Representation and Warranty.</strong> You represent and warrant that (i) your use of the Website will be in strict accordance with the IWAAT Privacy Policy, with this Agreement and with all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the United States or the country in which you reside) and (ii) your use of the Website will not infringe or misappropriate the intellectual property rights of any third party.</li>
	<li><strong>Indemnification.</strong> You agree to indemnify and hold harmless IWAAT, its contractors, and its licensors, and their respective directors, officers, employees and agents from and against any and all claims and expenses, including attorneys’ fees, arising out of your use of the Website, including but not limited to your violation of this Agreement.</li>
	<li><strong>Miscellaneous.</strong> This Agreement constitutes the entire agreement between IWAAT and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of IWAAT, or by the posting by IWAAT of a revised version. Except to the extent applicable law, if any, provides otherwise, this Agreement, any access to or use of the Website will be governed by the laws of the state of California, U.S.A., excluding its conflict of law provisions, and the proper venue for any disputes arising out of or relating to any of the same will be the state and federal courts located in San Francisco County, California. Except for claims for injunctive or equitable relief or claims regarding intellectual property rights (which may be brought in any competent court without the posting of a bond), any dispute arising under this Agreement shall be finally settled in accordance with the Comprehensive Arbitration Rules of the Judicial Arbitration and Mediation Service, Inc. (“JAMS”) by three arbitrators appointed in accordance with such Rules. The arbitration shall take place in San Francisco, California, in the English language and the arbitral decision may be enforced in any court. The prevailing party in any action or proceeding to enforce this Agreement shall be entitled to costs and attorneys’ fees. If any part of this Agreement is held invalid or unenforceable, that part will be construed to reflect the parties’ original intent, and the remaining portions will remain in full force and effect. A waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; IWAAT may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.</li>
	</ol>

</div>

<?php $this->load->view('includes/footer'); ?>